import be.ugent.rml.Executor;
import be.ugent.rml.Utils;
import be.ugent.rml.records.RecordsFactory;
import be.ugent.rml.store.QuadStore;
import be.ugent.rml.store.QuadStoreFactory;
import be.ugent.rml.store.RDF4JStore;
import be.ugent.rml.term.NamedNode;
import org.eclipse.rdf4j.repository.RepositoryConnection;
import org.eclipse.rdf4j.repository.http.HTTPRepository;
import org.eclipse.rdf4j.rio.RDFFormat;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

public class RMLPipeline {

    /**
     * Use RMLMapper to perform a mapping and load the generated RDF into GraphDB.
     */
    public static void main(String[] args) throws IOException {
        RMLPipeline pipeline = new RMLPipeline();

        File mappingFile = new File("./src/main/resources/rml/airports/airport-codes-small.mappings_1.ttl");
        File outputFile = new File("./src/main/resources/rml/airports/outputFile.ttl");

        // Run the RML Mapper and write the generated RDF to outputFile.ttl
        pipeline.runRMLMapper(mappingFile, outputFile);

        // Load generated RDF and ontology into GraphDB
        String repositoryName = "NAME";
        HTTPRepository repository = new HTTPRepository(
                "http://localhost:7200/repositories/" + repositoryName
        );

        RepositoryConnection connection = repository.getConnection();

        // Clear the repository before loading the new data
        connection.clear();

        // Start transaction
        connection.begin();

        try {
            // Load the ontology
            connection.add(
                    new FileInputStream("./src/main/resources/rml/airports/Airports.owl"),
                    "urn:base",
                    RDFFormat.TURTLE
            );

            // Load the RDF data generated by RMLMapper
            connection.add(
                    new FileInputStream(outputFile),
                    "urn:base",
                    RDFFormat.TURTLE
            );

            // Commit transaction
            connection.commit();

        } catch (IOException e) {
            e.printStackTrace();
            connection.rollback();

        } finally {
            connection.close();
            repository.shutDown();
        }
    }

    void runRMLMapper(File mappingFile, File outputFile) {
        try {
            // Extract base IRI from the mapping file
            String baseIRI = Utils.getBaseDirectiveTurtle(mappingFile.getAbsolutePath());

            // Read the RML mapping file
            InputStream mappingStream = new FileInputStream(mappingFile);

            // Parse the mapping into a QuadStore
            QuadStore rmlStore = QuadStoreFactory.read(mappingStream);
            mappingStream.close();

            // RecordsFactory resolves local input files referenced by the mapping
            RecordsFactory factory = new RecordsFactory(
                    mappingFile.getParent(),
                    mappingFile.getParent()
            );

            // Store for the generated RDF triples/quads
            QuadStore outputStore = new RDF4JStore();

            // Create the RMLMapper executor for v8.1.0
            Executor executor = new Executor(
                    rmlStore,
                    factory,
                    outputStore,
                    baseIRI,
                    null
            );

            // Execute the mapping and get the default output store
            QuadStore result = executor.execute(null)
                    .get(new NamedNode("rmlmapper://default.store"));

            // Write the result to a Turtle file
            OutputStream output = new FileOutputStream(outputFile);
            result.write(output, "turtle");
            output.close();

        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}